#!/usr/bin/python

"""This module bla bla bla."""
import category

def execute_categories_challenge():
    """This func bla bla bla."""
    print "Start challenge for Palymath Ventures"
    cat = category.Category(1)
    print cat

execute_categories_challenge()
